# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:  
- tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

